### ISSUE TITLE
What should the format of properties be?

### ISSUE THREAD

**Issue by wooorm** [wooorm/hast#1]
The current hast uses VProperties (from virtual-dom) for attributes on elements.

As [previously](https://github.com/wooorm/hast/tree/6ee4941f66d81c443e0eec430d29f7203045c05b) outlined in the readme:

>   VTree’s property format is built for speed, not for easy of use. Developers
>     need intimate knowledge of where things should go. Should `className` go on
>     `node.properties` or `node.properties.attributes`? (<small>Answer: “To set
>     className on SVG elements, it's necessary to use [attributes]”</small>).
>     That, and the hassle of using
>     `a = node.properties.attributes; a.className = (a.className ? a.className + ' ' : '') + 'foo';`
>     to add a class, simply sucks.

With hast, I’d like a single object (`properties`) instead of multiple (`properties`, `properties.*`, `properties.attributes`).

In addition, I’d like to support `Array`’s as values (in addition to `string`, `number`, or `boolean`) to reflect [“space separated tokens”](https://html.spec.whatwg.org/multipage/infrastructure.html#space-separated-tokens) and [“comma separated tokens”](https://html.spec.whatwg.org/multipage/infrastructure.html#comma-separated-tokens).
-   space separated values: `className`, `rel`, `httpEquiv`, `ping`, `sizes`, `sandbox`, `headers`, `sorted`, `accept-charset`, `for`, `autocomplete`, `autofill`, `itemtype`, `itemref`, `itemprop`, `accesskey`, `dropzone`;
-   comma separated values: `srcset`, `accept`, `coords`, `cols`, `rows`.

Most properties are space-separated, so that should be the default when compiling an Array property value, with a white-list for comma separated values.

Also, the `style` property should be an object mapping camelCased CSS properties, e.g., `borderBottomWidth`, to strings.

**Comment by wooorm** [comment]
Also, the parser should ensure all known “separated values” are split, and patch an array on `node.properties`. Plug-ins too should use arrays whenever possible for interoperability.

Regarding casing:
-   camelCase should be used for properties;
-   JS keywords must be changed, just like what the DOM does, to alternatives. `className` instead of `class`.
-   Known dash-cased attributes are compiled that way using a white-list, but in he hast model they’re camelCased.
-    Ambiguously cased properties, like the DOMs `maxlength`, should be properly cased: `maxLength`.
-    When compiling, duplicate attributes are NOT handled (as in, each compiled on the element)
  
  So:
  
  ``` json
  {
    "type": "element",
    "tagName": "div",
    "properties": {
      "foo": "bar",
      "Foo": "bar",
      "FOO": "bar"
    }
  }
  ```
  
  Yields:
  
  ``` html
  <div foo="bar" foo="bar" foo="bar"></div>
  ```

**Comment by eush77** [comment]
> Also, the parser should ensure all known “separated values” are split, and patch an array on `node.properties`. Plug-ins too should use arrays whenever possible for interoperability.

Are plugins required to handle both string and array values simultaneously?

``` js
if (typeof node.properties.className == 'string') {
  node.properties.className = node.properties.className.split(' ');
}

node.properties.className = node.properties.className || [];
node.properties.className.push(className);
```

If they are, it would be too much boilerplate IMO. Why not _require_ `className`, `rel`, `srcset`, etc to have array values? Then plugins would work with arrays exclusively, and hast would stringify these arrays properly with proper separators.

> Ambiguously cased properties, like the DOMs `maxlength`, should be properly cased: `maxLength`.

Nothing syntactically indicates that `maxlength` should be cased this way, and it also makes it ambiguous whether `myAttribute` refers to `myattribute` or `my-attribute`. For consistency, I suggest converting attribute names to lower case, and applying casing rules only to compound attribute names such as `http-equiv`. What do you think?

**Comment by wooorm** [comment]
@eush77 Thanks for the feedback!

> Why not require `className`, `rel`, `srcset`, etc to have array values.

I think it’s a subtle difference: I think plug-ins are allowed to break when `className` is not an array, and that plug-ins _should_ set arrays. However, hast itself should _not_ break when `className` is an array IMO, there doesn’t need to be any validation.

> Nothing syntactically indicates that `maxlength` should be cased this way, and it also makes it ambiguous whether `myAttribute` refers to `myattribute` or `my-attribute`. For consistency, I suggest converting attribute names to lower case, and applying casing rules only to compound attribute names such as `http-equiv`. What do you think?

Hast itself doesn’t care about casing: `acceptcharset`, `ACCEPTCHARSET`, `accept-charset` will all be treated the same (as a space-separated list). But there should be a standard for plug-ins.

Right now:
-   all [known](https://github.com/wooorm/property-information/blob/master/index.js) properties can be case-insensitive;
-   Known [dash-cased](https://github.com/wooorm/property-information/blob/ebd98b17f78375c7b7ec8227948f9aa19267ddf1/index.js#L231-L232) properties are handled properly;
-   Known [keyword](https://github.com/wooorm/property-information/blob/ebd98b17f78375c7b7ec8227948f9aa19267ddf1/index.js#L229-L230) properties are handled properly;
-   Unknown properties are transformed to [param-case](https://www.npmjs.com/package/param-case#usage) — therefore, they cannot be camel-cased if the `attribute` doesn’t have dashes.

I think the default should be to dash-ise all properties (similar to what happens when setting `document.body.dataset.fooBar = ''`, namely, a `data-foo-bar` attribute is added), lift this requirement for known attributes, and in fact `require` the use of [`tabIndex`](https://github.com/wooorm/property-information/blob/ebd98b17f78375c7b7ec8227948f9aa19267ddf1/index.js#L176) over `tabindex`.

Luckily, angular’s custom attributes are also often dash-cased, but unfortunately [WAI-ARIA](http://www.w3.org/TR/wai-aria/appendices#quickref_header) is not :(

**Comment by voischev** [comment]
Good point if you parse this, and safe html structure ;)

#### input html

``` html
<div class="a b c"
        data-foo: "{
            foo: 'bar',
            baz: function() {}
        }",
        disabled
    >
        My text
   </div>
```

in plugin — disabled -> disabled="disabled"

#### output html

``` html
<div class="a b c"
        data-foo: "{
            foo: 'bar',
            baz: function() {}
        }",
        disabled="disabled"
    >
        My text
   </div>
```

Look at PostCSS parser https://github.com/postcss/postcss/blob/master/lib/parser.es6

**Comment by wooorm** [comment]
@voischev Thanks for the response, however, I’m not sure what you’re trying to say. First off, `data-foo: "...` is invalid HTML, did you mean `data-foo="...`?

Currently, according to the plan described above, the following HTML:

``` html
<div class="a b c"
    data-foo="{
        foo: 'bar',
        baz: function() {}
    }"
    disabled
  >
    My text
</div>
```

Yields, the following syntax tree:

``` json
{
  "type": "root",
  "children": [
    {
      "type": "element",
      "tagName": "div",
      "properties": {
        "className": [
          "a",
          "b",
          "c"
        ],
        "dataFoo": "{\n        foo: 'bar',\n        baz: function() {}\n    }",
        "disabled": true
      },
      "children": [
        {
          "type": "text",
          "value": "\n    My text\n",
          "position": {
            "start": {
              "line": 7,
              "column": 4,
              "offset": 105
            },
            "end": {
              "line": 9,
              "column": 1,
              "offset": 117
            }
          }
        }
      ],
      "position": {
        "start": {
          "line": 1,
          "column": 1,
          "offset": 0
        },
        "end": {
          "line": 9,
          "column": 7,
          "offset": 123
        }
      }
    },
    {
      "type": "text",
      "value": "\n",
      "position": {
        "start": {
          "line": 9,
          "column": 7,
          "offset": 124
        },
        "end": {
          "line": 10,
          "column": 1,
          "offset": 124
        }
      }
    }
  ]
}
```

Which compiles to:

``` html
<div class="a b c" data-foo="{
        foo: &#39;bar&#39;,
        baz: function() {}
    }" disabled>
    My text
</div>
```

Also: that should I check out in PostCSS? Could you [link](http://stackoverflow.com/a/31282559) to what you’d like me to see?

**Comment by voischev** [comment]
> is invalid HTML

of course, my bad.

The result is not enough to keep the structure of HTML.
Saving the position of rows between attributes that make a big difference. Otherwise, it lost a lot of privileges of PostHTML, or in other parsers, because he is already is able to do the same.

About a PostCSS
PostCSS parser does so: 
input css

``` css
.a,
.b,
.c 
{ a: b; }
```

It does not change the structure output css, if it does not ask

``` css
.a, .b, .c /* ??? not like what I was writing */
{ a: b; }
```

PostCSS parser keeps the structure as it was!

**Comment by wooorm** [comment]
@voischev Are you saying that PostHTML _does_ support white-space between attributes? I just checked, and I cannot reproduce:

The following HTML:

``` html
<div class="a b c"
    data-foo="{
        foo: 'bar',
        baz: function() {}
    }"
    disabled
  >
    My text
</div>
```

And the below code:

``` js
var post = require('posthtml');

post()
    .process(doc)
    .then(function(result) {
        console.log(result.html);
    });
```

Yields:

``` html
<div class="a b c" data-foo="{
        foo: 'bar',
        baz: function() {}
    }" disabled>
    My text
</div>
```

To be honest, I don’t really care about multiple white-spaces between attributes!

I’d rather have an [_ast_ over a _cst_](http://eli.thegreenplace.net/2009/02/16/abstract-vs-concrete-syntax-trees/): it makes things a lot easier for plug-ins!

**Comment by voischev** [comment]
:) I'm just saying that this parser and a would be a great advantage over PostHTML

**Comment by wooorm** [comment]
Oh haha, now I see! Thanks, I’ll investigate but as stated above, not very high on my TODO list :wink:

**Comment by wooorm** [comment]
The current set-up is fine! Arrays for space-separated lists and comma-separated lists, booleans for boolean things, strings for string values, etcetera...
