### ISSUE TITLE
What’s the difference between hast and PostHTML

### ISSUE THREAD

**Issue by eush77** [wooorm/hast#3]
[PostHTML](https://github.com/posthtml/posthtml) looks very similar to hast and its plugins are to some extent [reminiscent](https://github.com/theprotein/posthtml-extend-attrs/blob/43a472982580436858038a78900f94fbf4438758/index.js) of mdast's attacher—transformer pattern.

The main difference seems to be that hast is going to use the same tree format as mdast and retext and will benefit from [unist](https://github.com/wooorm/unist) utils, but maybe there are some other notable differences.

Have you seen that project before and how can you compare it to hast?

**Comment by wooorm** [comment]
@eush77 Nice, very interesting! :)
-   I like he unist syntax tree haha :stuck_out_tongue:, I think PostHTML uses the default exposed from `htmlparser2`?
-   I think, what we’re doing with properties, namely making them native to JS, is really useful for plug-in authors!
-   `position` is really important: without it errors and warnings are useless, with positional information, things get really awesome!
-   Using both `vfile`’s and a `tree` to represent a processed document, a standardised place for [messages](https://github.com/wooorm/vfile#vfilemessages) and a place for [metadata](https://github.com/wooorm/vfile#vfilenamespacekey) is also a plus for more advanced tooling!

I’ll have to dig deeper for more though!

**Comment by voischev** [comment]
It may be needed to help PostHTML, not to make a new one? ;)

**Comment by wooorm** [comment]
@voischev Interesting. I do agree that work should be kept to a minimum, and _if_ both projects do the same, it would be better to just create one project instead.

However, I do know that the background of **hast**, being built on unified, unist, and vfile (modules being used by retext and mdast), provides solid and extensive support for plug-ins and tooling. In my opinion this makes hast theoretically at least different from (maybe better than) PostHTML.

I haven’t written plug-ins for **hast** yet, so I cannot really show the difference between the two projects yet. I’d like to though: do you have any preferred plug-ins you’d like to see written with hast? I was thinking about [posthtml-doctype](https://github.com/posthtml/posthtml-doctype/blob/master/index.js), which is simple enough to compare both projects objectively!

**Comment by voischev** [comment]
@wooorm
By the way. You have seen [posthtml-textr](https://github.com/voischev/posthtml-textr) plugin? This is a good example of that Retext can also work with PostHTML

**Comment by wooorm** [comment]
@voischev Agreed! And I just published the [hast-doctype](https://github.com/wooorm/hast-doctype), pretty similar to how [posthtml-doctype](https://github.com/posthtml/posthtml-doctype) works!

**Comment by voischev** [comment]
@wooorm and [posthtml-retext](https://github.com/voischev/posthtml-retext) published ;)

**Comment by wooorm** [comment]
I’m “quite” close to releasing a stable version of what used to be known as “hast”, as **rehype**; not yet though, I’d first like to create some useful example plug-ins.

I believe I presented my case regarding the difference above, so I’m closing this!

Cheers :)
